---

- name: Create service file
  ansible.builtin.template:
    src: automate.j2
    dest: /etc/systemd/system/automate.service
    mode: 0644
  notify: Reload systemctl

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Stop service
  ansible.builtin.systemd:
    name: automate
    state: stopped
  notify: Start service

- name: Clone repo
  ansible.builtin.git:
    repo: "{{ lookup('ansible.builtin.env', 'GITHUB_REPO_URL') }}"
    dest: /opt/automate
    single_branch: true
    version: "{{ lookup('ansible.builtin.env', 'GITHUB_SHA') }}"
    refspec: "{{ lookup('ansible.builtin.env', 'GITHUB_REF') }}"
  notify:
    - Create env
    - Install packages based on package.json
    - Build project
    - Start service
