---

- name: Configure droplets
  hosts: "{{ lookup('ansible.builtin.env', 'DEPLOYMENT_ENV') }}"
  gather_facts: false
  pre_tasks:
    - name: Include droplets role
      ansible.builtin.include_role:
        name: droplets
        apply:
          become: false
    - name: Gather facts
      ansible.builtin.setup:
  roles:
    - provision
    - auth
    - hostname
    - hosts
    - ntp
    - ssh
    - timezone
    - ufw
    - unattended-upgrades
    - geerlingguy.nodejs
    - basic_setup
  remote_user: root
  become: true

- name: Configure domains
  hosts: local
  tasks:
    - name: Setup CNAME record
      community.general.cloudflare_dns:
        api_token: "{{ lookup('ansible.builtin.env', 'CF_TOKEN') }}"
        zone: auto-mate.cc
        record: "{{ item.domain }}"
        type: CNAME
        value: "{{ item.target }}"
        solo: true
      loop: "{{ domains }}"
