---

- name: Local run
  hosts: local
  tasks:
      - name: Create droplet
        ansible.builtin.include_role:
            name: droplets
        loop: "{{ groups['cloud'] }}"
      - name: Wait to allow dns changes to propogate
        ansible.builtin.pause:
          minutes: 1
      - name: Refresh inventory after pause
        ansible.builtin.meta: refresh_inventory

- name: Configure droplets
  hosts: cloud
  roles:
      - provision
      - auth
      - hostname
      - hosts
      - ntp
      - ssh
      - timezone
      - ufw
      - unattended-upgrades
      - geerlingguy.nodejs
      - basic_setup
  remote_user: root
  become: true
