---

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades

- name: Setup unattended-upgrades config
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644

- name: Setup unattended-upgrades interval config
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: 0644
