---

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades

- name: Setup unattended-upgrades config
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Setup unattended-upgrades interval config
  template:
    src:  20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
