name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: [18.x]

    - name: Install dependencies
      run: npm ci

    - name: Check Node.js version
      run: node -v

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Execute unit tests (Vitest)
      run: npm run vitest:test

    - name: Execute end-to-end tests (Playwright)
      run: npm run playwright:test

    - name: Generate code coverage report
      run: npm run coverage

